
on:
  push:
    branches: main

name: Continuous integration

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        style: [all, default, minimal]
        rust:
          - stable
        
        include:
          - style: all
            flags: '--all-features'
          - style: default
            flags: ''
          - style: minimal
            flags: '--no-default-features'
        exclude:
          - platform: ubuntu-latest
            style: default
          - platform: macos-latest
            style: minimal

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

    

      # run script show realpath
      - name: Clone patch Anki
        run: sh ./clone_patch_anki
          
          

  

          


